# https://taskfile.dev

version: '3'

env:
  AWS_DEFAULT_REGION: ap-southeast-1
  CDK_DEFAULT_REGION: ap-southeast-1
  CDK_DEFAULT_ACCOUNT: 
    sh: |
      if command -v aws >/dev/null 2>&1; then
        aws sts get-caller-identity --query Account --output text 2>/dev/null || true
      else
        echo ""
      fi


includes:
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
  infra:
    taskfile: ./infra/Taskfile.yml
    dir: ./infra
  collector:
    taskfile: ./collector/Taskfile.yml
    dir: ./collector
tasks:
  run:server:
    desc: Run the local API server on :8080
    cmds:
      - bash ./hack/run-server.sh

  run:frontend:
    desc: Open the minimal HTMX frontend
    cmds:
      - bash ./hack/run-frontend.sh

  run:local:
    desc: Start server and open frontend
    cmds:
      - bash ./hack/run-local.sh

  test:all:
    desc: Run tests across collector, server, and infra
    cmds:
      - task: collector:test
      - task: server:test
      - task: infra:test

  coverage:collector:
    desc: Collector coverage report (atomic)
    cmds:
      - cd collector && go test ./... -covermode=atomic -coverprofile=coverage.out
      - cd collector && go tool cover -func=coverage.out | tail -n 1

  coverage:server:
    desc: Server coverage report (atomic)
    cmds:
      - cd server && go test ./... -covermode=atomic -coverprofile=coverage.out
      - cd server && go tool cover -func=coverage.out | tail -n 1

  coverage:infra:
    desc: Infra coverage report (atomic)
    cmds:
      - cd infra && go test ./... -covermode=atomic -coverprofile=coverage.out
      - cd infra && go tool cover -func=coverage.out | tail -n 1

  coverage:all:
    desc: Run coverage for collector, server, infra (no frontend)
    cmds:
      - task: coverage:collector
      - task: coverage:server
      - task: coverage:infra

 