# https://taskfile.dev

version: '3'

env:
  AWS_DEFAULT_REGION: ap-southeast-1
  CDK_DEFAULT_REGION: ap-southeast-1
  CDK_DEFAULT_ACCOUNT: 
    sh: aws sts get-caller-identity --query Account --output text


includes:
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
  infra:
    taskfile: ./infra/Taskfile.yml
    dir: ./infra
  collector:
    taskfile: ./collector/Taskfile.yml
    dir: ./collector
tasks:
  run:server:
    desc: Run the local API server on :8080
    cmds:
      - bash ./hack/run-server.sh

  run:frontend:
    desc: Open the minimal HTMX frontend
    cmds:
      - bash ./hack/run-frontend.sh

  run:local:
    desc: Start server and open frontend
    cmds:
      - bash ./hack/run-local.sh

  test:all:
    desc: Run tests across collector, server, and infra
    cmds:
      - task: collector:test
      - task: server:test
      - task: infra:test


 