version: '3'

services:
  click_server:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./dbfiles:/var/lib/clickhouse

  click_client:
    image: clickhouse/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity