# https://taskfile.dev

version: '3'

tasks:
  test:
    desc: Run collector tests
    cmds:
      - go test ./... -v

  coverage:
    desc: Collector coverage (atomic)
    cmds:
      - go test ./... -covermode=atomic -coverprofile=coverage.out
      - go tool cover -func=coverage.out | tail -n 1

  tidy:
    desc: Go mod tidy
    cmds:
      - go mod tidy

  run:
    desc: Run the collector CLI (pass flags after --)
    cmds:
      - |
        ARGS="{{.CLI_ARGS}}"
        if [ -z "$ARGS" ]; then
          echo "No CLI args supplied; running demo scrape for Accenture (override via task collector:run -- --keyword <TERM>)."
          ARGS="--c Accenture"
        fi
        go run . $ARGS

  build:
    desc: Build collector binary into ../dist/collector
    cmds:
      - mkdir -p ../dist
      - go build -o ../dist/collector .

  prime-lake:
    desc: Prime the parquet lake/catalog then reindex (pass flags after --, filters optional)
    cmds:
      - |
        cache_dir="${AUSTENDER_CACHE_DIR:-$HOME/.cache/austender}"
        go run . cache {{.CLI_ARGS}}
        go run . reindex-lake --cache-dir "$cache_dir"
