# https://taskfile.dev

version: '3'

tasks:
  test:
    desc: Run collector tests
    cmds:
      - go test ./... -v

  tidy:
    desc: Go mod tidy
    cmds:
      - go mod tidy

  run:
    desc: Run the collector CLI (pass flags after --)
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task collector:run -- [args]";
          echo "Example: task collector:run -- --keyword KPMG";
          exit 0;
        fi
      - go run . {{.CLI_ARGS}}
