# https://taskfile.dev

version: '3'

tasks:
  test:
    desc: Run collector tests
    cmds:
      - go test ./... -v

  tidy:
    desc: Go mod tidy
    cmds:
      - go mod tidy

  run:
    desc: Run the collector CLI (pass flags after --)
    cmds:
      - |
        ARGS="{{.CLI_ARGS}}"
        if [ -z "$ARGS" ]; then
          echo "No CLI args supplied; running demo scrape for Accenture (override via task collector:run -- --keyword <TERM>)."
          ARGS="--c Accenture"
        fi
        go run . $ARGS
